SELECT B.AUTHOR_ID,C.AUTHOR_NAME,B.CATEGORY,SUM((SALES * PRICE)) AS TOTAL_SALES
# SELECT *
FROM BOOK_SALES AS A
JOIN BOOK AS B ON A.BOOK_ID = B.BOOK_ID
JOIN AUTHOR AS C ON B.AUTHOR_ID = C.AUTHOR_ID
WHERE LEFT(A.SALES_DATE,7) = '2022-01'
GROUP BY B.AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID, CATEGORY DESC;
