SELECT B.PRODUCT_CODE,SUM(A.SALES_AMOUNT) * B.PRICE AS SALES
FROM OFFLINE_SALE AS A
JOIN PRODUCT AS B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_ID
ORDER BY SUM(A.SALES_AMOUNT) * B.PRICE DESC, B.PRODUCT_CODE;