SELECT LEFT(SALES_DATE,10) AS SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT FROM ONLINE_SALE WHERE MONTH(SALES_DATE) = 3
UNION
SELECT LEFT(SALES_DATE,10) AS SALES_DATE,PRODUCT_ID,NULL AS USER_ID,SALES_AMOUNT FROM OFFLINE_SALE WHERE MONTH(SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;