SELECT A.ID,
    CASE 
        WHEN A.RNK = 1 THEN 'CRITICAL'
        WHEN A.RNK = 2 THEN 'HIGH'
        WHEN A.RNK = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, 
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS RNK
    FROM ECOLI_DATA 
) AS A
ORDER BY A.ID;