WITH RECURSIVE G AS(
    SELECT ID,PARENT_ID,1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT A.ID,A.PARENT_ID,B.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA AS A
    JOIN G AS B ON A.PARENT_ID = B.ID
)
SELECT COUNT(ID) AS COUNT, GENERATION
FROM G
WHERE ID NOT IN(
    SELECT DISTINCT PARENT_ID 
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;