SELECT A.PRODUCT_ID,PRODUCT_NAME,SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_ORDER AS A
JOIN FOOD_PRODUCT AS B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE LEFT(PRODUCE_DATE,7) = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;