SELECT 
    A.HISTORY_ID,
    FLOOR(
        CASE
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 < 7 THEN B.DAILY_FEE * (DATEDIFF(A.END_DATE, A.START_DATE) + 1)
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 < 30 THEN B.DAILY_FEE * (DATEDIFF(A.END_DATE, A.START_DATE) + 1) * ((100 - D1.DISCOUNT_RATE) / 100)
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 < 90 THEN B.DAILY_FEE * (DATEDIFF(A.END_DATE, A.START_DATE) + 1) * ((100 - D2.DISCOUNT_RATE) / 100)
            ELSE B.DAILY_FEE * (DATEDIFF(A.END_DATE, A.START_DATE) + 1) * ((100 - D3.DISCOUNT_RATE) / 100)
        END
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
JOIN CAR_RENTAL_COMPANY_CAR AS B ON A.CAR_ID = B.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D1 ON B.CAR_TYPE = D1.CAR_TYPE AND D1.DURATION_TYPE = '7일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D2 ON B.CAR_TYPE = D2.CAR_TYPE AND D2.DURATION_TYPE = '30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D3 ON B.CAR_TYPE = D3.CAR_TYPE AND D3.DURATION_TYPE = '90일 이상'
WHERE B.CAR_TYPE = '트럭'
ORDER BY FEE DESC, A.HISTORY_ID DESC;