SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL FROM FIRST_HALF GROUP BY FLAVOR
    UNION ALL 
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL FROM JULY GROUP BY FLAVOR
) AS COMBINED
GROUP BY FLAVOR
ORDER BY SUM(TOTAL) DESC
LIMIT 3;