SELECT A.APNT_NO,B.PT_NAME,B.PT_NO,C.MCDP_CD,C.DR_NAME,A.APNT_YMD
FROM APPOINTMENT AS A
JOIN PATIENT AS B ON A.PT_NO = B.PT_NO
JOIN DOCTOR AS C ON A.MDDR_ID = C.DR_ID
WHERE LEFT(A.APNT_YMD,10) = '2022-04-13' AND A.APNT_CNCL_YN = 'N' AND C.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD;