SELECT ID,EMAIL,FIRST_NAME,LAST_NAME
FROM DEVELOPERS AS A
JOIN (
    SELECT SUM(CODE) AS CODE 
    FROM SKILLCODES 
    WHERE CATEGORY 
    LIKE 'Front%') AS B
ON (A.SKILL_CODE & B.CODE) > 0
ORDER BY A.ID;