SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') as DATE_OF_BIRTH 
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL AND SUBSTRING(DATE_OF_BIRTH,6,2) = '03' AND GENDER = 'W'
ORDER BY MEMBER_ID ASC;