SELECT MONTH(START_DATE) AS MONTH,CAR_ID,COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    # WHERE LEFT(7,START_DATE) BETWEEN '2022-08' AND '2022-10'
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY CAR_ID,MONTH(START_DATE)
ORDER BY MONTH,CAR_ID DESC
