SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, B.MAXSIZE - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A  
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS Y, MAX(SIZE_OF_COLONY) AS MAXSIZE 
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) B ON YEAR(A.DIFFERENTIATION_DATE) = Y
ORDER BY YEAR(A.DIFFERENTIATION_DATE), B.MAXSIZE - A.SIZE_OF_COLONY;