SELECT TITLE,B.BOARD_ID,REPLY_ID,B.WRITER_ID,B.CONTENTS,LEFT(B.CREATED_DATE,10) AS CREATED_DATE
FROM USED_GOODS_BOARD A 
JOIN USED_GOODS_REPLY B ON A.BOARD_ID = B.BOARD_ID
WHERE LEFT(A.CREATED_DATE,7) = '2022-10'
ORDER BY B.CREATED_DATE ASC,TITLE ASC;