SELECT B.TITLE,B.BOARD_ID,R.REPLY_ID,R.WRITER_ID,R.CONTENTS,LEFT(R.CREATED_DATE,10) AS CREATED_DATE
FROM USED_GOODS_REPLY AS R 
JOIN USED_GOODS_BOARD AS B ON R.BOARD_ID = B.BOARD_ID
WHERE SUBSTRING(B.CREATED_DATE,1,7) = '2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;